// Generated by CoffeeScript 1.6.3
(function() {
  var PORT, app, express, stylus;

  express = require('express');

  app = express();

  stylus = require('stylus');

  app.use(stylus.middleware({
    debug: true,
    src: __dirname + '/app/css',
    dest: __dirname + '/app/css',
    compile: function(str) {
      return stylus(str).set('compress', true);
    }
  }));

  app.use(express["static"](__dirname + '/app'));

  app.set('views', __dirname + '/app/partials');

  app.engine('jade', require('jade').__express);

  app.get('/', function(req, res) {
    return res.render('home.jade');
  });

  app.get('/from/markdown/to/html', function(req, res, next) {
    return console.log('not implemenetd');
  });

  PORT = 7793;

  app.listen(PORT);

  console.log('Express server listening on port ' + PORT + '.');

}).call(this);
