// Generated by CoffeeScript 1.6.3
(function() {
  var PORT, app, express, pandoc;

  express = require('express');

  app = express();

  app.use(require('stylus').middleware(__dirname + '/static'));

  app.set('views', __dirname + '/partials');

  app.engine('jade', require('jade').__express);

  app.use(express["static"](__dirname + '/static'));

  pandoc = require('pdc');

  app.use(express.bodyParser());

  PORT = 7793;

  app.listen(PORT);

  console.log('Express server listening on port ' + PORT + '.');

  app.get('/', function(req, res) {
    return res.render('edit.jade');
  });

  app.post('/render/pdf', function(req, res) {
    console.log('REQUEST', req.body);
    /* console.log req.body.markdown
    opts = []
    result = ''
    pandoc req.body.markdown, 'markdown', 'pdf', opts,
        (err, result) ->
            if err is null then pdf = result
    res.return pdf
    */

    return res.send(req.body);
  });

}).call(this);
